### ISSUE TITLE
Import ROIs issues

### ISSUE THREAD

**Issue by jzaremba** [losonczylab/sima#23]
1) If a pair of datasets fails to transform, there is no error message, it just quietly returns.

2) The affine transform is run from sima.misc, UI_tSeries.transform is used elsewhere, so the results are not necessarily the same.

3) The transform does not use the processed image, which is probably the main reason that it gives different results from the transform calculated by UI_tSeries.transform.

**Comment by nbdanielson** [comment]
ROI Buddy now uses Registration Anchors if they are available.  Otherwise it defaults to an affine transform based on the image.  

In importing ROIs (the ImagingDataset method), you can choose which registration method you would like to use.  If this is the same method as ROI buddy, the polygons will overlap exactly in show-all mode.  Otherwise we would not expect them to overlap
