### ISSUE TITLE
Manual ROI alignment/registration in ROI buddy

### ISSUE THREAD

**Issue by mattjdavis** [losonczylab/sima#49]
Some datasets in which the same cell population was imaged, resulted in dissimilar projected time series, at least according to the ROI buddy algorithm, to match the data sets in alignment mode. It would be a nice feature to override the automatic matching and allow manual alignment, where all the ROIs can be shifted at once or individually as needed. This could be especially useful for hand drawn generated in imagej.

**Comment by jzaremba** [comment]
We're still working on cleaning it up a bit and putting together a tutorial, but we have something implemented that should fix these cases. You can now manually choose known anchor points that are common to all sets and use them for registration instead of the automatic registration. The manual anchor point mode should never fail and can be more accurate if the automatic registration gets confused by changes in intensity across sessions.

We've additionally added a piecewise-affine manual registration mode which does a better job registering when there are local warps of the tissue.

**Comment by mattjdavis** [comment]
Sounds great! Looking forward to it.

**Comment by nbdanielson** [comment]
This is now fully implemented and seems to be working.  This will be available in version 1
